"""Every name a faction ships, in one table: `python3 -m sagekit names <faction> [--write]`.

Own names are chosen by hand (a free letter on EA's sheet name, a free suffix on a model) and must
not collide with EA's or another building's. The recipes and their build records hold the truth;
this collects them, so a new building (or faction) picks its names against the whole list, and
assets/<faction>/NAMES.md is regenerated rather than kept by hand."""
import os

from . import paths
from .registry import building_ids, load
from .workspace import Workspace


def rows(faction):
    """[(building id, EA model, shipped model, {EA texture: ours}, [derived/lifecycle models], house model)]."""
    out = []
    for bid in building_ids():
        if not bid.startswith(faction + "/"):
            continue
        b, ws = load(bid), None
        ws = Workspace(b)
        tex = dict(b.texture_names())
        tex.update(ws.variants)
        tex.update(ws.normal_variants)
        lives = sorted(set(ws.derived) | set(ws.lifecycle))
        house = (ws.house or {}).get("model", "")
        out.append((bid, b.source, b.shipped_name(b.source), tex,
                    [b.shipped_name(m) for m in lives], house))
    return out


def taken(table):
    """{EA texture: [our names]}: the letters and suffixes already used on each EA sheet."""
    out = {}
    for _, _, _, tex, _, _ in table:
        for ea, ours in tex.items():
            if "_nrm" not in ea.lower():
                out.setdefault(ea.lower(), set()).add(ours)
    return {k: sorted(v, key=str.lower) for k, v in sorted(out.items())}


def markdown(faction):
    table = rows(faction)
    lines = ["# %s: shipped names" % faction.capitalize(), "",
             "Generated by `python3 -m sagekit names %s --write`; do not edit by hand." % faction,
             "Build records fill the last two columns, so rebuild a building before regenerating.", "",
             "| Building | EA model | Ships as | Own textures (EA -> ours) | Lifecycle models | House model |",
             "|---|---|---|---|---|---|"]
    for bid, src, ship, tex, lives, house in table:
        t = "<br>".join("%s -> %s" % kv for kv in sorted(tex.items(), key=lambda kv: kv[0].lower()))
        lines.append("| %s | %s | %s | %s | %s | %s |" % (
            bid.split("/", 1)[1], src, ship if ship != src else "(same)", t, " ".join(lives) or "-", house or "-"))
    shared = next((load(bid).style.shared_sheets for bid in building_ids() if bid.startswith(faction + "/")), {})
    if shared:
        lines += ["", "## Faction copies of other factions' sheets (style.shared_sheets)", ""]
        lines += ["- `%s` -> `%s`" % kv for kv in sorted(shared.items())]
    night = next((load(bid).style.night for bid in building_ids() if bid.startswith(faction + "/")), None)
    if night:                                   # the faction's night-light texture (sagekit/nightlights.py)
        lines += ["", "## Night lights (style.night)", "", "- `%s`" % night.texture]
    lines += ["", "## Names taken per EA sheet", ""]
    lines += ["- `%s`: %s" % (ea, ", ".join(v)) for ea, v in taken(table).items()]
    return "\n".join(lines) + "\n"


def ea_texture_stems(install):
    """Every texture name (lower-case stem) EA's archives provide or its pristine caches file."""
    stems = {m.split("\\")[-1][:-4] for m in install.members("art\\compiledtextures") if m.endswith((".dds", ".tga"))}
    for c in install.asset_caches().values():
        stems |= {n.decode("latin-1")[:-4] for n in c.texture_names() if n.endswith((b".tga", b".dds"))}
    return stems


def recipe_texture_stems():
    """Every own texture name (lower-case stem) the recipes of all factions pin or derive, with the
    state variants their build records hold."""
    out = set()
    for bid in building_ids():
        b = load(bid)
        out |= {t[:-4].lower() for t in b.texture_names().values()}
        out |= {t[:-4].lower() for t in list(Workspace(b).variants.values()) + list(Workspace(b).normal_variants.values())}
    return out


def check_free(b, ea_stems):
    """Refuse an own texture name EA's files already use: the game would load EA's file for it."""
    for ea, own in b.texture_names().items():
        if own[:-4].lower() in ea_stems:
            raise ValueError("own texture %s (for %s) is a name EA's archives or caches use - pick another" % (own, ea))


def free_texture(original, taken, letters="HXBCDEFGJKLMNPQRSTVWYZ"):
    """An own name for sheet `original` of the same length (W3D patches names in place): its last
    letter replaced, H first as own_texture_name does, such that neither the name nor any
    `<name>_...` (its normal map and state variants) is in `taken` (lower-case stems)."""
    stem = original[:-4]
    for c in letters:
        low = (stem[:-1] + c).lower()
        if low != stem.lower() and low not in taken and not any(t.startswith(low + "_") for t in taken):
            return stem[:-1] + c + original[-4:]
    raise ValueError("no free own name for %s" % original)


def write(faction):
    p = os.path.join(paths.REPO, "assets", faction, "NAMES.md")
    with open(p, "w") as fh:
        fh.write(markdown(faction))
    return p
